### ISSUE TITLE
Method for documenting changes between cli versions

### ISSUE THREAD

**Issue by s1cyan** [kabanero-io/kabanero-command-line#102]
In each release we would like to have a summary of "what's changed" in the cli from this version and the last.
We need to figure out some method to keep track and that and how we present that in future releases. Ex: from 0.1.0 to 0.2.0 the login method changed

**Comment by stephenkinder** [comment]
I am assuming this is related to the CLI because of the repo, but composed with all the other issues -- just a tad bit more detail about what needs a "what is changed" would be copasetic.

**Comment by s1cyan** [comment]
Create a runbook that provides instructions for how to create a release as well as how to write up the updates (go through commit history from last release)

**Comment by s1cyan** [comment]
We have a template for a release.md somewhere - ask gary (foundation?)
