### ISSUE TITLE
Long term solution for building darwin builds w Travis

### ISSUE THREAD

**Issue by s1cyan** [kabanero-io/kabanero-command-line#104]
Continuation of the work from issue #98 

**Problem**: Travis doesn't seem to play well with cross compilation when building for a release. The osx builds need to be built with the env variable CGO_ENABLED=1 to address the vpn host resolution issue (98).
The current solution is that I build the osx binary locally and upload it to the release, but its definitely not ideal. 

**Note**: Appsody also has this problem, let them know when a travis soln is found.

**Comment by kaczyns** [comment]
I have heard of other projects using `qemu` to build on other platforms - it's what the kabanero-operator will probably do to provide power and Z containers.  Do we know if `qemu` can be used to produce a native mac environment on x86?

**Comment by s1cyan** [comment]
Looks like there is an option for Mac OS X 10.5 guest installation on `qemu`. 
I got the travis build to build the osx binary with cgo enabled (connected issue) so should I keep looking into `qemu`?

**Comment by kaczyns** [comment]
No - I was just trying to be helpful in case you didn't have another solution :-)
