### ISSUE TITLE
Onboard to just output tekton url

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/kabanero-command-line#109]
Remove parameters for onboard command and

format the output pretty for kabanero onboard. should be just a tekton url after unblocked

don't just display as raw json

**Comment by stephenkinder** [comment]
@davco01a is this for the CLI or the server?

**Comment by s1cyan** [comment]
why would we format onboard when it doesn't do anything?

**Comment by davco01a** [comment]
It is informative for what Champ needs to do, provides instructions on how to proceed.  We shouldn't have json coming out, should be a minor change.

**Comment by davco01a** [comment]
@stephenkinder This is for the CLI

**Comment by s1cyan** [comment]
@davco01a the change that got put in, still takes the gituser to be onboarded in the body. should i change this to 1 parameter instead of 2 to 0.

**Comment by s1cyan** [comment]
Onboard was changed to just take 1 param (the user to be onboarded)
vs the old command that took the user and the repo to add them to
