### ISSUE TITLE
rename darwin binary to macos

### ISSUE THREAD

**Issue by tseelbach** [kabanero-io/kabanero-command-line#122]
We should name  the darwin download of the Kabanero cli as macos.  Whilst it may be strictly be a darwin build, do we care about people using darwin outside of macos?  I've personally not come across anyone doing this, and labelling it darwin adds a little confusion to those who are not familiar with the heritage of MacOS.

**Comment by s1cyan** [comment]
If we make this change - are we changing just the name of the binary 
Or are we intending to do a whole refactor of our Makefile to change references to darwin to osx

**Comment by tseelbach** [comment]
i suggest s/darwin/macos/g in the Makefile.  That should cover 95% of the change.   there may be some other changes needed as well

**Comment by tseelbach** [comment]
go support "darwin" as the os so that needs to remain.  So best option is probably to rename the output

**Comment by s1cyan** [comment]
Soln adds a predeploy step to travis to rename the darwin binary. 
In the future we might want to change the name from the makefile, but i think it makes more sense to change it from travis
