### ISSUE TITLE
Doc in CLI readme that changes in GIT Hub can be slow to show up

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/kabanero-command-line#124]
doc in CLI readme that changes in GIT Hub can be slow to show up or do we assume that Champ will be experienced enough to know this?

https://stackoverflow.com/questions/24851824/how-long-does-it-take-for-github-page-to-show-changes-after-changing-index-html

@ralanlittle @stephenkinder

**Comment by davco01a** [comment]
spoke with @tseelbach and we'll add some kind of disclaimer to README for Champ to explain about the delay:

e.g.

`Modifications to the curated collection may be delayed in git hub and may not be reflected immediately in LIST or SYNC display output`

**Comment by davco01a** [comment]
this should be nea the top of the README so it will generalize to both sections

**Comment by s1cyan** [comment]
In the connected PR I made the note about github being slow to update in the `list` and `sync` functions rather than in the beginning readme. 
My thinking is that I don't want to litter the start of the README with caveats on when the command line doesn't function the way it is intended to.

**Comment by davco01a** [comment]
merged
