### ISSUE TITLE
"/v1/version" endpoint being changed to "/v1/image" endpoint

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/kabanero-command-line#125]
json returned will be:

{"image":"kabanero/kabanero/kabanero-command-line-services:0.3.0"}

**Comment by s1cyan** [comment]
new `version` output
```
claudias-mbp kabanero-command-line =>./build/kabanero version
kabanero cli version: 0.1.0
kabanero command line service image: davco01a/kabanero-command-line-services:latest
```

**Comment by kaczyns** [comment]
I think that you are going to regret not having some kind of version tag, or commit hash, in the `kabanero command line service image` output.  Knowing what image you are using isn't going to help you understand if a user has a fix installed, if they copied the image to another location.  And it's certainly not going to help if it says `latest`.

**Comment by davco01a** [comment]
I discussed with @kaczyns and while it may not be an optimal solution, for now it's an improvement over what we had previously.  We will at least be able to determine which sancitioned semver image the customer is running with.

Weaknesses with this approach are if L3 is developing fixes we may not know which image was used for the fix or test if the tag just says `latest`.

Temporarily L3 can have custom named tags instead of `latest` to identify an image.

In the long term we could use the SHA of the image or a commit level to uniquely identify the image.
