### ISSUE TITLE
modify onboard so it has no parms

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/kabanero-command-line#128]
modify onboard so it has no parms

Parms are not needed since it's only displaying the URL for the tekton dashboard

**Comment by marikaj123** [comment]
@davco01a - Hi Dave, why the label SVT was added?

**Comment by s1cyan** [comment]
I'm closing this issue and adding it to one of the open issues for onboard. onboard doesn't even display the url for the tekton dashboard right now
