### ISSUE TITLE
Improve labels for Collections in list command

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/kabanero-command-line#129]
change `Collection Name` to `Kabanero Instance Collections`

change `Curated Collections` to `GitHub Curated Collections`

**Comment by marikaj123** [comment]
@davco01a - Hi Dave, why the label SVT was added?

**Comment by jantley-ibm** [comment]
@davco01a shouldn't that be GitHub Curated Collections ?

**Comment by davco01a** [comment]
@marikaj123 These concerns were brought up by @mtamboli so it originated from SVT

**Comment by davco01a** [comment]
also make the underline dashes as long as the Words in the heading
