### ISSUE TITLE
deactivate could check that status actually gets changed to inactive, not just desiredState

### ISSUE THREAD

**Issue by mtamboli** [kabanero-io/kabanero-command-line#130]
See below that 3 collections are deactivated, but only 2 are getting activated with sync.

Here are the steps to re-create:
* Rebuild collections with a new collection java-ee and updates to existing one. https://github.com/mtamboli/collections/releases/download/v0.3.1/kabanero-index.yaml
* Update Kabanero CR instance with the new collection
* It was decided by Champ to deactivate a few collections temporarily including java-ee
* It was decided to sync all the collections and I at this point others were reactivated but not java-ee which was also expected to be re-activated.

```
$./kabanero deactivate java-ee
Collection name: java-ee deactivated
$ ./kabanero deactivate java-microprofile
Collection name: java-microprofile deactivated
$ ./kabanero deactivate java-spring-boot2
Collection name: java-spring-boot2 deactivated

$ ./kabanero sync

Collection Name		Version	Status
----			----	----
java-microprofile	0.2.18	inactive ==> active
java-spring-boot2	0.3.15	inactive ==> active
```

https://github.com/mtamboli/collections/releases/download/v0.3.1/kabanero-index.yaml used by kabanero has `java-ee` collection.

**Comment by mtamboli** [comment]
We need to assess the impact of this bug before we decide if this is a not a stop-ship.

**Comment by davco01a** [comment]
Which one is the new collection?

I need a complete description of the scenario, the full sequence of steps.  Thank you

**Comment by davco01a** [comment]
this should be moved to command-line-services repo

**Comment by davco01a** [comment]
How is the SHA derived?
```
- id: default
    sha256: 6a9f9e50382d652e92df6b88e72dbe25501126fa1ed47d028e8d45d27cec39ce
    url: https://github.com/mtamboli/collections/releases/download/v0.3.1/incubator.common.pipeline.default.tar.gz
```

**Comment by davco01a** [comment]
The deactivate code is correctly setting the java-ee desiredState to inactive but the collections controller is not getting the status to inactive

Sync doesn't change the status to active because it is already active

**Comment by davco01a** [comment]
deactivate should check that status actually gets changed to inactive, not just desiredState

this may require a sleep of 5-10 seconds to ensure the collections controller can make the status change

**Comment by davco01a** [comment]
moving to command line services repo

**Comment by gecock** [comment]
@davco01a can you provide the link to the new issue please?

**Comment by davco01a** [comment]
https://github.com/kabanero-io/kabanero-command-line-services/issues/77

**Comment by mtamboli** [comment]
@davco01a I see that this issue and reference issues are closed. So did you already change the behavior where deactivate will wait for kabanero operator to make sure that the deactivation really happens? So if deactivate does not work for any reason, CLI will report that deactivate was not successful. Champ is doing activation for a good reason and status returned will be important.

**Comment by davco01a** [comment]
sorry I moved this issue to here:  https://github.com/kabanero-io/kabanero-command-line-services/issues/88
