### ISSUE TITLE
Enhancements to Kabanero CLI `list` command

### ISSUE THREAD

**Issue by mtamboli** [kabanero-io/kabanero-command-line#141]
**Describe the bug**

Below things will make kabanero list command more useful:

1. (MOVED TO ISSUE https://github.com/kabanero-io/kabanero-command-line/issues/150)  ~ It will be good to list the collection hub location for both operator (active) and Github. These collection/stack versions may not change but the could still be a new change in new collection hub. So it will be good to know for Champ if the 2 URLs are of different version ~ 

Also, if someone just updated current release without changing the URL, displaying URL may help will that too.
2. CLI should also indicate any issues/errors during error condition:

Reference issue: https://github.com/kabanero-io/kabanero-operator/issues/311
>  it would be nice if the CLI could show somehow that there is a problem. We may need to brainstorm about how to do this - from the operator's perspective, there is a valid version of the java-microprofile collection active... and therefore the CLI may be showing the right thing. But then again, there is a (newer?) version of the collection that is not active yet, and will probably replace the currently active

```
$ ./kabanero list

Kabanero Instance Collections	Version	Status
-----------------------------	-------	------
java-ee				0.1.1	active
java-microprofile		0.2.19	active
java-spring-boot2		0.3.16	active
nodejs				0.2.6	active
nodejs-express			0.2.8	active
nodejs-loopback			0.1.6	active
nodejs				0.2.6	obsolete

GitHub Curated Collections	Version
--------------------------	-------
java-ee				0.1.1
java-microprofile		0.2.19
java-spring-boot2		0.3.16
nodejs-express			0.2.8
nodejs-loopback			0.1.6

```
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

OCP 4.2/kabanero 0.3.0

**Additional context**

**Comment by marikaj123** [comment]
@davco01a - Since the issue was opened under CLI, I would appriciate your help if you can assign it  to the appropriate person. Thank you.

**Comment by s1cyan** [comment]
For the first suggestion: How about putting the urls at the top before the table?
Ex:
```
Kabanero Instance Collections	: <kaburl>
GitHub Curated Collections	: <githuburl> 

Kabanero Instance Collections	Version	Status
-----------------------------	-------	------
java-ee				0.1.1	active
java-microprofile		0.2.19	active
java-spring-boot2		0.3.16	active
...
```

For the second suggestion. We currently put a star next to new collections that are not in the active collections, what if we did something similar with version and put a star next to the version number of the github collection if it is mismatched 
Ex:
```

Kabanero Instance Collections	Version	Status
-----------------------------	-------	------
java-ee				0.1.1	active
java-microprofile		0.2.19	active
java-spring-boot2		0.3.16	active


GitHub Curated Collections	Version
--------------------------	-------
java-ee				0.1.1
java-microprofile		0.2.20*
java-spring-boot2		0.3.16

```

**Comment by davco01a** [comment]
You should not see this in 0.4.0, we no longer mark them as obsolete but automatically deactivate them if they are no longer in GitHub collectio

**Comment by davco01a** [comment]
anyway please try to recreate with 040 RC and update the issue

**Comment by davco01a** [comment]
agree with @s1cyan

**Comment by s1cyan** [comment]
closes issue 2 that this post addressed 
note: issue one was moved to #150 

> You should not see obsolete listed
in 0.4.0, we no longer mark them as obsolete but automatically deactivate them if they are no longer in GitHub collection
