### ISSUE TITLE
login command does not take password from stdin

### ISSUE THREAD

**Issue by chainhead** [kabanero-io/kabanero-command-line#142]
**Describe the bug**
`kabanero login` does not take password from `stdin`

**To Reproduce**
`kabanero login url -u user -p` or `kabanero login url -u user ` does not prompt user to enter password manually. Forces the password to be typed in clear on command line. 

**Expected behavior**
Allow password typing in `stdin`

**Desktop (please complete the following information):**
 - OS: RHEL 7.7
 - Version kabanero cli version: 0.3.0

**Comment by s1cyan** [comment]
@chainhead  we would like to implement this in a future version of the cli. Due to our very limited testing, it is possible that doing it from stdin will cause it to not work for windows. I am working on getting a windows license to be able to get this out.

**Comment by s1cyan** [comment]
implemented- tested on win & macos
