### ISSUE TITLE
kabanero login does not work with GitHub personal access token

### ISSUE THREAD

**Issue by chainhead** [kabanero-io/kabanero-command-line#143]
**Describe the bug**
Login with GitHub personal access token does not work.

**To Reproduce**
`kabanero login URL -u githubUserId -p PersonalAccessToken` 

**Result
`[Error] Your session may have expired or the credentials entered may be invalid`
This is wrong because I can clone with personal access token successfully.

**Expected behavior**
Successful login.

**Desktop (please complete the following information):**
 - OS: RHEL 7.7
 - Version 0.3.0

**Comment by s1cyan** [comment]
@chainhead  have you followed the instructions to configure the CLI?

**Comment by s1cyan** [comment]
@chainhead  i have found multiple users mistakenly not configuring their authorization for the CLI and running into the same error message. I have opened up an issue to return a different error message to notify users that they need to do so. https://github.com/kabanero-io/kabanero-command-line/issues/145

**Comment by s1cyan** [comment]
closing due to no follow up
