### ISSUE TITLE
CLI commands should show any error on the operator

### ISSUE THREAD

**Issue by mtamboli** [kabanero-io/kabanero-command-line#152]
**Describe the bug**

Updated Kabanero operator with collections URL which was not valid. So there was an error on the operator. But CLI did not reflect any error.

* If the index was not correct, how id sync working?

```
$ ./kabanero sync
kabanero instance collections is already synchronized with the github curated collections
```
* List does not return anything without showing any error
```
 ./kabanero list
Kabanero Instance Collections	Version	Status
-----------------------------	-------	------

GitHub Curated Collections	Version
--------------------------	-------
```
**To Reproduce**
1. Provide incorrect collections URL
2. Kabanero operant will show error
3. Configure CLI with the kabanero instance 
4. No errors returned by CLI commands

**Expected behavior**

I expect Kabanero CLI to show some error when operator is showing errors.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by s1cyan** [comment]
@davco01a  will add more exception handling and then those exceptions will be handled in the cli (put in general send error handling rather than specifically on sync)

**Comment by marikaj123** [comment]
@mtamboli - The serviceability issue is targeted for Kabanero release 0.6.0

**Comment by marikaj123** [comment]
@davco01a - Please inform us if the fix is on track for Kabanero 0.6.0.

**Comment by marikaj123** [comment]
According to @davco01a, the team is looking into conatining the fix in the GMC build.

**Comment by s1cyan** [comment]
Dave is sending operator status error as a 503. We are already using 503 for unreachable urls, we will have to additionally parse this error code for multiple meanings. 
We will have to transition from taking the error code and spitting out our own message to just taking the error and extracting the error message that dave send with it. (this might be a bigger overhaul issue later on)

**Comment by marikaj123** [comment]
Going into Kabanero GMC 0.6.0

**Comment by s1cyan** [comment]
closed - see referenced issue for change made to show 503 errors 
503s will be sent when there is an error on the operator

**Comment by mtamboli** [comment]
Hi Dave, I see this is fixed. Error message is helpful. But not sure why usage is displayed? I think that is confusing as the command is correct. Thoughts?
```
./kabanero list
HTTP Status ƨ: The CLI service could not read the repository URL specification(s) from the Kabanero CR
Error: Invalid Response
Usage:
  kabanero list  [flags]

Flags:
  -h, --help   help for list

Global Flags:
  -v, --verbose   Turns on debug output and logging to a file in $HOME/.kabanero/logs

[Error] Invalid Response

```
