### ISSUE TITLE
Detect if CLI and CLI service versions collections/stacks compatible (0.6.0 <>) 

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/kabanero-command-line#155]
Detect if CLI and CLI service levels are mismatched, and issue warning

1. Cache values on login
2. If they mismatch issue warning on every command
3. Or just issue warning at login and on version functions

**Comment by s1cyan** [comment]
this could get very tricky with semver stuff. and our 0.x.x level stuff doesn't follow that but we have versions in the 0.x.x that would be incompatible with other 0.x.x versions for the service/cli

**Comment by davco01a** [comment]
This may require that the image path (which is returned from the version endpoint) be also returned on login so it can be cached.  We may need to keep it simple and require an exact semver match, otherwise put out a warning or at least match on major and minor digits...we should discuss w semver experts.

**Comment by davco01a** [comment]
First implementation: just check on version function to compare the docker tag for the cli service to the cli version level if they don't match and put out a warning message if they don't match.  Doc that consumer should run version function after login.

Down the road, have login call version and cache the docker tag, then on every function call (SYNC, LIST, DEACTIVATE etc) compare the cached value for the docker tag with the cli version level and put out a warning message if they don't match

**Comment by s1cyan** [comment]
After the Cloud Integration & public developer playback steve said the version level mismatch is just going to be checking the difference between 0.6.0 due to the collections & stacks difference. 
A more nuanced version check is something that needs to be discussed further
