### ISSUE TITLE
README updates

### ISSUE THREAD

**Issue by tseelbach** [kabanero-io/kabanero-command-line#165]
in the generated README,  a few issues:
1. It points to this doc which is 404:  https://kabanero.io/docs/ref/general/github-authorization.html

2. Update the -v option to include brew log location:
$HOME/.kabanero/logs or, if installed via brew, in ~/Library/Logs/kabanero/

**Comment by marikaj123** [comment]
@tseelbach - Hi tom, is this opened for your team.  If yes, please move it to backlog.
