### ISSUE TITLE
Error handling overhaul

### ISSUE THREAD

**Issue by s1cyan** [kabanero-io/kabanero-command-line#169]
Initially we only had a few known error codes being sent by cli services, so we would be parsing the error status code and composing our own error message to indicate what is going on. As we have further developed, services is sending more error codes (see full list of error codes and meanings https://github.com/kabanero-io/kabanero-command-line/issues/137. 
This issue is for going back and changing how we do error handling throughout the CLI, to no longer send out our own message and instead change to just parse the error message that services sends with the error code

**Comment by marikaj123** [comment]
According to Dave, it is going into Kabanero GMC 0.6.0

**Comment by tseelbach** [comment]
When error messages are displayed, the usage should not be displayed since its not a usage error.   If  we cannot contain suppressing the usage message with this refactor of error handling, then it can be split into a new issue.

**Comment by marikaj123** [comment]
@s1cyan - is looking to have the fix in by today and cut a new rc release.
