### ISSUE TITLE
Remove the Usability Error that comes up for any error

### ISSUE THREAD

**Issue by s1cyan** [kabanero-io/kabanero-command-line#180]
**Is your feature request related to a problem? Please describe.**
For any error in the CLI, the cobra prompt for how to use the CLI will show up with the error output. It's messy and unnecessary when -v and -h are unhelpful to the situation when you just want to see what specifically went wrong. For something like not enough arguments for a command, the usability prompt can come up.

Ex:
From current:
```
Error: Login to your kabanero instance
Usage:
  kabanero list  [flags]

Flags:
  -h, --help   help for list

Global Flags:
  -v, --verbose   Turns on debug output and logging to a file in $HOME/.kabanero/logs

[Error] Login to your kabanero instance
```
to just:
`Login to your kabanero instance`

**Comment by mtamboli** [comment]
This is another example when it is unnecessary and confusing to display usage since the command syntax is correct:
```
kabanero list
HTTP Status ƨ: The CLI service could not read the repository URL specification(s) from the Kabanero CR
Error: Invalid Response
Usage:
  kabanero list  [flags]
Flags:
  -h, --help   help for list
Global Flags:
  -v, --verbose   Turns on debug output and logging to a file in $HOME/.kabanero/logs
[Error] Invalid Response
```

**Comment by s1cyan** [comment]
@mtamboli  yeah this error output will be attached to any possible error in the CLI so these are definitely not the only case. Cobra automatically spits this out for anything i return as an error. 
I have already found a workaround, that we will likely by implementing in 0.7.0
