### ISSUE TITLE
JWT stored in config.yaml is not fully encrypted

### ISSUE THREAD

**Issue by tseelbach** [kabanero-io/kabanero-command-line#186]
We use a JWT to allow multiple CLI invocations without authenticating each time.  On kabanero login the JWT is stored in ~/.kabanero/config.yaml and it is deleted on logout.  Critical parts like PAT within the JWT are encrypted by the cli-service (server side) but other claims are not encrypted.  If the JWT was stolen it could be used to run CLI commands until expiration (configurable in the Kabanero CRD). 

We should consider encrypting more of the JWT, either the whole thing (using JWE?) or we should encrypt additional claims.

**Comment by s1cyan** [comment]
Was told we can encrypt on our side and just keep the key in the same file that we store the jwt in
