### ISSUE TITLE
Internal Server error reported at null

### ISSUE THREAD

**Issue by tseelbach** [kabanero-io/kabanero-command-line#191]
cli should report "500 Internal Server Error" or similar.  Not report null

 tsees-mbp in ~/Downloads/kabanero-0.6.0-macos-amd64
○ → ./kabanero version -v -x
[Debug] Logging to file /Users/tsee/.kabanero/logs/kabanero2020-02-27T22-02-33.340373.log
[Debug] Kabanero config directory: /Users/tsee/.kabanero
[Debug] Config file name: /Users/tsee/.kabanero/config.yaml
[Debug] config file used: /Users/tsee/.kabanero/config.yaml
[Info] kabanero cli version: 0.6.0
[Info] requestDump: GET /v1/image HTTP/1.1
Host: kabanero-cli-kabanero.apps.nowyouretalking.os.fyre.ibm.com
Authorization: Bearer 
my token
Content-Type: application/json

[Info] responseDump: HTTP/1.1 500 Internal Server Error
Connection: close
Content-Length: 62
Content-Language: en-US
Content-Type: application/octet-stream
Date: Fri, 28 Feb 2020 03:02:33 GMT

{"message":"Unexpected exception: null, cause: null occurred"}
[Debug] HTTP Status 500 : Unexpected exception: null, cause: null occurred
Unexpected exception: null, cause: null occurred

 2020-02-27 22:02:33 ⌚  tsees-mbp in ~/Downloads/kabanero-0.6.0-macos-amd64
○ → ./kabanero version 
kabanero cli version: 0.6.0
Unexpected exception: null, cause: null occurred

**Comment by s1cyan** [comment]
@tseelbach I thought we agreed that the cli for the most part would simply be ferrying the error message through. Are you saying that we are going to be adding another special error code handling case? If not this should be opened on the CLI services repo to change the message that is passed through

**Comment by davco01a** [comment]
this resulted from some NPEs that needed debugging when the initial Pentest fixes went in for multiple login and JWTs.  They've been fixed and this should not recur

**Comment by s1cyan** [comment]
It has also been decided that the CLI will not be showing the numerical error codes with the output when errors occur

**Comment by tseelbach** [comment]
please link the PR whhere this was fixed

**Comment by davco01a** [comment]
will be fixed when this is merged:

https://github.com/kabanero-io/kabanero-command-line-services/pull/130
