### ISSUE TITLE
Formatting issues

### ISSUE THREAD

**Issue by jgawor** [kabanero-io/kabanero-command-line#199]
* The initial usage word wrapping is mixed and confusing:
```
$ ./kabanero 
**kabanero** is a command line interface for managing the stacks in a Kabanero 
environment, as well as to on-board the people that will use 
the environment to build applications.

Before using the cli please configure the github authorization for the cli service. Steps can be found in the following documentation: https://kabanero.io/docs/ref/general/configuration/github-authorization.html
```

Please use consistent line wrapping. Besides, I'm not sure all that text is necessary anyway.

* There is also some  inconsistency in the same out between `kabanero instance` vs `Kabanero instance`. That's all over the place.

**Comment by s1cyan** [comment]
Resolved the random newline in this pr : https://github.com/kabanero-io/kabanero-command-line/pull/200

I agree with the unnecessary wording, bringing in @jantley-ibm to help w the text revision

**Comment by marikaj123** [comment]
According to Jarek, this is not a stopsship issue for Kabanero 0.6.0

**Comment by davco01a** [comment]
Approved by DOC team
