### ISSUE TITLE
TLS certificate solution

### ISSUE THREAD

**Issue by s1cyan** [kabanero-io/kabanero-command-line#209]
**Describe the bug**
Security issue with the cli.
We hardcoded InsecureSkipVerify: true in https://github.com/kabanero-io/kabanero-command-line/blob/master/cmd/sync.go#L51. that disables any certificate validation and therefore the cli will talk to any https server with valid or invalid certificates. Certificate validation should be explicitly disabled by the user via some argument. There are many examples of that: oc login --insecure-skip-tls-verify, buildah --tls-verify false, cf login --skip-ssl-validation .  As a result of InsecureSkipVerify, the kabanero login command will pass your credential to whatever site is specified in the CLI.

**We currently use** : `TLSClientConfig: &tls.Config{InsecureSkipVerify: true},` in the go code for sending requests because the service only has a self signed cert. If we did not skip the insecure verify, the requests would only work for endpoints with CA certs which the service isnt, and if we had manually gone into the backend pod to get the self signed cert to store locally. 

**Proposed solution** : 

- We are going to remove `TLSClientConfig: &tls.Config{InsecureSkipVerify: true},` from the client config initialization and let it fail and then generate a prompt to the user, similar to what ssh does, indicating that the kabanero endpoint is not a secure endpoint and yes/no to continue connecting. If they say yes we add back the `InsecureSkipVerify: true` to the client config. Otherwise we stop all other command from happening unless they say yes or get the cert to store locally. 
- Investigate/disable trust of well known CAs, so we do not send any data to well known / general https enabled sites
- Add flag to pass in the cert authority location. Similar to how kubectl and oc work. Also add flag for insecureTLS true

**Comment by jgawor** [comment]
That's a good solution for interactive mode but need a solution for non-interactive mode as well. For example, when running via a script. We need to be able to pass in a password and indicate insecure connections are ok.

**Comment by s1cyan** [comment]
Have code for `--certificate-authority` and `--insecure-skip-tls-verify` as flags but having difficulty getting to the liberty server to do REST calls. Calls work fine if i set `--insecure-skip-tls-verify=true`

**Comment by marikaj123** [comment]
@s1cyan -  Any idea at what Kabanero release would the fix become available?

**Comment by s1cyan** [comment]
@marikaj123 hopefully by 0.9.0. I was under the impression that this TLS cert issue would be resolved by the other security TLS security secure endpoints issue, but it turns out they are not so I have to get back to this next iteration

**Comment by s1cyan** [comment]
after update to CLI services pod to use reecrypt, i now get 
`[Debug] No response from url: kabanero-cli-kabanero.apps.oheightoh.os.fyre.ibm.com Post https://kabanero-cli-kabanero.apps.oheightoh.os.fyre.ibm.com/login: x509: certificate is valid for kabanero-cli.kabanero.svc, kabanero-cli.kabanero.svc.cluster.local, not kabanero-cli-kabanero.apps.<clustername>.os.fyre.ibm.com`
 The cert seems to be for some generic common name `kabanero-cli.kabanero.svc` and not the cluster. I got the cert using the openssl command :
`openssl s_client -connect kabanero-cli-kabanero.apps.<name>.os.fyre.ibm.com:443 -servername kabanero-cli-kabanero.apps.<name>.os.fyre.ibm.com` as well as tried the one from the browser

**Comment by s1cyan** [comment]
after changes to the CLI service yaml we got the cert, working, Waiting on operator changes before adding this to a release
