### ISSUE TITLE
Fix version compatibility check

### ISSUE THREAD

**Issue by jgawor** [kabanero-io/kabanero-command-line#225]
The CLI code performs compatibility check which retrieves the image tag of the command line service and parses the tag version (https://github.com/kabanero-io/kabanero-command-line/blob/master/cmd/login.go#L46). This will not work once the tag changes to a digest (needed for air-gap installs).

**Comment by s1cyan** [comment]
@jgawor  Can you explain this air-gap install?  I'm not sure I understand what can happen with this air-gap situation, does this mean that the image tag value could be a digest value? Not clear on when someone would do that to the CLI service.

**Comment by jgawor** [comment]
@s1cyan all image references will change from tags to digests. for example, `kabanero/kabanero-command-line-services:0.8.0` from now on will look like `kabanero/kabanero-command-line-services@12346`. that will break the current compatibility check in the cli.

**Comment by davco01a** [comment]
@jgawor The CLI service retrieves the metadata used in the compare, are you saying that the tag metadata for the image will no longer exist alongside the digest ?

**Comment by jgawor** [comment]
@davco01a the `image` metadata of the cli service will no longer specify a tag. it will specify digest instead.

**Comment by s1cyan** [comment]
Clarified that the information about the version of the CLI that the CLI gets from services will not change. We will still get the 0.x.y and the version check will stay the same

**Comment by davco01a** [comment]
The new GO service will return a version number.

The old java service may need to be modified to return a fixed server tag, since that code base is going to be frozen.

@jgawor please advise

**Comment by s1cyan** [comment]
should be fixed by : https://github.com/kabanero-io/kabanero-command-line/pull/237
