### ISSUE TITLE
changes due to Devfiles 

### ISSUE THREAD

**Issue by marikaj123** [kabanero-io/kabanero-command-line#230]
Epic: Converge on common developer tools - Odo/Devfiles

**Comment by s1cyan** [comment]
@marikaj123  if this is an issue for a REST API - shouldn't this be a cli-services issue? Unless this is something that the CLI should be be doing, in which I would appreciate more details

**Comment by anneqm** [comment]
@s1cyan understand this to be update the REST API to work with the new devfile format.

**Comment by marikaj123** [comment]
@s1cyan - Tom is helping with updating the child issues under the Odo/Devfile Epic and including the appropriate child issues accordingly.

**Comment by s1cyan** [comment]
ambiguous issue - closing
