### ISSUE TITLE
Onboard command on on Kabanero CLI

### ISSUE THREAD

**Issue by marikaj123** [kabanero-io/kabanero-command-line#233]
Logs
(Run the Must Gather Scripts for Kabanero or the Must Gather Scripts for ICPA and post the logs to an accessible location)

Environment Information

    Kabanero/ICPA Version: 0.9.0
    OpenShift Version: OCP 4.4
    Platform (Fyre, IBM Cloud, etc): Fyre

Additional context

    Public Issue (if applicable):

Test Execution Record Reference
(If found while running a TER add a link to the TER here. If not, you can remove this section.)

**Comment by s1cyan** [comment]
Onboard is going away, along with the rest of the CLI client
