### ISSUE TITLE
Address vulnerability scan results

### ISSUE THREAD

**Issue by mchenggit** [kabanero-io/kabanero-command-line#238]

**Comment by mchenggit** [comment]
Move from sha256 to sha512 for local encryption.

**Comment by s1cyan** [comment]
While I can make a 512 bit size key, the current aes package does not support making a cipher out of a key bigger than 256. 

I found the following resources for why the 512 key is not necessary/no possible:
https://crypto.stackexchange.com/questions/20253/why-we-cant-implement-aes-512-key-size/20258
https://crypto.stackexchange.com/questions/58777/is-the-cipher-kalyna-with-a-512-bit-key-length-more-secure-aes-with-a-256-bit
It seems like the Kalina cipher supports the 512 key size, but there is not Kalina support in golang, and it seems more like a research topic than implementation currently.

**Comment by mchenggit** [comment]
Is it possible to use sha512 hash with 256 bit key? If it is, please go with that.

**Comment by s1cyan** [comment]
I'm not sure what you mean. The actual key is just the time stamp of when we create it, I use the sha512 hash to encrypt the key. I use the aes standard package to create the cipher from the hashed key

**Comment by s1cyan** [comment]
scan marked false positive
