### ISSUE TITLE
Onboard Command

### ISSUE THREAD

**Issue by s1cyan** [kabanero-io/kabanero-command-line#24]

**Comment by s1cyan** [comment]
Call to the microservice implemented. But the implementation itself is in progress and just ouputs to champ to manually onboard someone

**Comment by marikaj123** [comment]
@s1cyan. davco01a , and tseelbach - is the issue ready to close?

**Comment by marikaj123** [comment]
@davco01a - Is the work for this issue continue to be targeted for v0.3.0 release?
