### ISSUE TITLE
Travis Build of Kabanero CLI

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/kabanero-command-line#27]
Travis Build of Kabanero CLI

**Comment by s1cyan** [comment]
We currently do not have anything set up for setting up the travis go environment with all the dependencies that we have. (Some go deps equivalent needs to be done)
Appsody has a separate controller within their org that they point to an install into their environment.
We either need to make some similar controller or figure out what we can do to configure the env

**Comment by tseelbach** [comment]
kabanero-command-line git project is based on appsody/appsody CLI.   Our travis build is failing with what appears to be a failure to download go dependencies.  But I compared our travis build output line by line with appsody and I don't see why appsody dependencies resolve, and kabanero dependencies do not (same packages as appsody: cobra, viper, ...).  
This is the error:
[36mINFO[0m [lintersdb] Active 12 linters: [deadcode errcheck gofmt golint gosimple govet ineffassign staticcheck structcheck typecheck unused varcheck] 
[36mINFO[0m [lintersdb] Optimized sublinters [staticcheck gosimple unused] into metalinter megacheck 
[36mINFO[0m [loader] Go packages loading at mode load deps types and syntax took 1.253059873s 
[31mERRO[0m Running error: context loading failed: failed to load program with go/packages: go [list -e -json -compiled -test=true -export=false -deps=true -find=false -- ./...]: exit status 1: go build github.com/kabanero-command-line/cmd: no Go files in 
go build github.com/mitchellh/go-homedir: no Go files in 
go build github.com/spf13/cobra: no Go files in 
go build github.com/spf13/cobra/doc: no Go files in 
go build github.com/spf13/pflag: no Go files in 
go build github.com/spf13/viper: no Go files in 
go build k8s.io/klog: no Go files in

**Comment by tseelbach** [comment]
problem is that we are missing /vendor dir with our dependencies.    Need to run dep ensure and then push the /vendor dir
https://golang.github.io/dep/docs/introduction.html

**Comment by kaczyns** [comment]
FWIW we had trouble when the directory path to our project was not complete WRT github.com.
For example, if we had `gopath/src/github.com/kabanero-operator/pkg/mysource.go` we would get the error you saw.
But if we had `gopath/src/github.com/kabanero-io/kabanero-operator/pkg/mysource.go` everything was fine.  Missing the `kabanero-io` directory messed up the dependencies.
However then we did what you're doing and switched to using the vendor directory, so it's all a moot point now.

**Comment by s1cyan** [comment]
Travis build for lint/ empty test are green - next step is to try cutting a release on my fork and get travis to make a build for it

**Comment by s1cyan** [comment]
travis build works for building + publishing builds for new releases
https://github.com/kabanero-io/kabanero-command-line/releases/tag/v0.2.0rc1
