### ISSUE TITLE
versioninfo

### ISSUE THREAD

**Issue by tseelbach** [kabanero-io/kabanero-command-line#28]
cli that returns all the installed kabanero component names and versions

**Comment by s1cyan** [comment]
if this is a different version command from  #26 , going to need to specify 
That lists the version of the cli

**Comment by s1cyan** [comment]
version implementation now includes the cli and the microservice version 
https://github.com/kabanero-io/kabanero-command-line/pull/55

**Comment by tseelbach** [comment]
Done!   If we want to expand versioninfo we can open a new issue.
