### ISSUE TITLE
Add results to the examples in the doc, once the results are defined.

### ISSUE THREAD

**Issue by ralanlittle** [kabanero-io/kabanero-command-line#3]
Document the output from CLI runs for each CLI action

**Comment by mingcyu** [comment]
@davco01a Is product documentation needed for this work item?

**Comment by marikaj123** [comment]
@tseelbach and @davco01a and @jantley-ibm - This issue is a child of an Epic and needs the label release. The Epic will need to close by this Friday.

**Comment by davco01a** [comment]
working on it

**Comment by davco01a** [comment]
./kabanero list output:

```
Collection Name		Version	Status
----			----	----
java-microprofile	0.2.11	active
java-spring-boot2	0.3.9	active
nodejs			0.2.5	active
nodejs-express		0.2.5	active
nodejs-loopback		0.1.4	active

Curated Collections	Version
----			----
java-microprofile	0.2.11
java-spring-boot2	0.3.9
nodejs-express		0.2.5
nodejs-loopback		0.1.4
nodejs			0.2.5
```

**Comment by davco01a** [comment]
./kabanero deactivate nodejs
Collection name: nodejs deactivated

**Comment by davco01a** [comment]
./kabanero version
kabanero cli version: 0.1.0
kabanero command line service version: 0.2.0

**Comment by davco01a** [comment]
./kabanero onboard jane github.com/myorg/myrepo
```
{
	"message": "Command development in progress, please go to the tekton dashboard in your browser and manually configure the webhook For gituser: jane"
}
```

**Comment by marikaj123** [comment]
@davco01a - PR is ready to merge and the issue can get closed after.  Thank you.

**Comment by davco01a** [comment]
./kabanero logout
Logged out of kab instance: <KABANERO_CLI_URL>
