### ISSUE TITLE
Create the Kabanero Management CLI for Collections and Hub Management

### ISSUE THREAD

**Issue by nateziemann** [kabanero-io/kabanero-command-line#33]

**Comment by stephenkinder** [comment]
@tseelbach if this not a dashboard or website feature, do you feel this a duplicate of the Epic for the initial drop of the CLI microservice? If so can you close it?

**Comment by davco01a** [comment]
This seems like a dupe, we should probably cose it @tseelbach

**Comment by s1cyan** [comment]
the cli is created
