### ISSUE TITLE
change login cmd to use  option flags for user, pw, and pwt

### ISSUE THREAD

**Issue by tseelbach** [kabanero-io/kabanero-command-line#48]
Currently login parameters are positional.  The problem with this is that it will be difficult to debug login problems because we cannot store the command line parameters in a debug log file because we don't want to log the password or PAT.   I propose we change to use option flags for id/pw/pat so that we can log  the ID and the URL.

Using option flags is also more consistent with "oc login" and "ibmcloud login" which use option flags.

Proposal is to roughly follow the syntax of "oc login"

Proposed usage:

kabanero login -h
Login to a Kabanero instance using github credentials, and store a temporary access token for subsequent command line calls.
The temporary authentication token will be stored in your-home-directory/.kabanero/config.yaml.
Use your github userid and either password or Personal Access Token (PAT).

Usage:
  kabanero login [URL] [flags]

Examples:
      
  # Log in to the given server with the given credentials (will not prompt interactively)
  kabanero login localhost:8443 --username=myuser --password=mypass

Options:
  -u, --username='': Username
  -p, --password='': Password
  -t, --pat='': Personal Access Token

May also want to prompt for Username and Password if not entered on cmd line.

**Comment by s1cyan** [comment]
implemented in connected PR : 
-u, --username='': Username
-p, --password='': Password/PAT
i dont think that -t is very user friendly. Nothing is stopping a user from putting an incorrect/expired PAT into password and having it show up in the logs that they put in a password and not a PAT. In the end a password/PAT gets sent in the same value to be authorized
