### ISSUE TITLE
Instructions for Todd on how to code URL to master collection

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/kabanero-command-line#52]
Todd needs to know how to properly code the URL for index.yaml in Champ's cloned repo in the CRD for the kabanero operator so it can be read by the REST GET in the Kab CLI microservice:

e.g. 

https://raw.github.com/kabanero-io/kabanero-command-line-services/master/kabanero.yaml

**Comment by mingcyu** [comment]
@davco01a Is product documentation needed for this?

**Comment by davco01a** [comment]
Already covered here:

https://github.com/kabanero-io/docs/blob/b5f89aeb520f8ec5ea7017f384ac3aca668f83f6/ref/general/collection-building.adoc
