### ISSUE TITLE
Please verify that JWT is in Auth header for kab cli logout function

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/kabanero-command-line#65]
Please verify that JWT is in Auth header for kab cli logout function

If it is, just close this issue

**Comment by s1cyan** [comment]
basically all commands that aren't login require the jwt so the code i wrote adds the jwt to authorization header to any call that is not for login 
```
	if !strings.Contains(url, "login") {
		req.Header.Set("Authorization", string(cliConfig.GetString("jwt")))
		if cliConfig.GetString("jwt") == "" {
			return resp, errors.New("Login to your kabanero instance")
		}
	}
```
