### ISSUE TITLE
Jane can be on-boarded  to the team environment for the Collection.

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/kabanero-command-line#82]
One of the key tenants of Kabanero is the low-touch management of enterprise approved micro-service programming languages and the curated CRI-O containers that host them.  

The developer needs to be told of both the enterprise curated Kabanero repository location for usage with Kabanero development open-source projects Appsody/Codewind.  

The developer also needs to have assistance in setting up the Kabanero/Tekton webhooks to connect their Github repository to the supporting Kabanero Instance hosted in an OKD managed Kubernetes cluster.

**Comment by s1cyan** [comment]
is this basically the issue open for the onboard command? 
https://github.com/kabanero-io/kabanero-command-line/issues/24
