### ISSUE TITLE
ambiguous term `kabanero instance`

### ISSUE THREAD

**Issue by gireeshpunathil** [kabanero-io/kabanero-command-line#85]
`Login to a Kabanero instance` in the README.txt - this looks vague to me.

The example 
`kabanero login my.kabaneroInstance.io -u myGithubID -p myGithubPassword` is equally abstract.

what this `instance` really is? `https://kabanero.io`? or a downstream github project that hosts a kabanero collection? or something else?

**Comment by stephenkinder** [comment]
A Kabanero Instance is an instantiation of a Kabanero Foundation in an OKD-managed Kubernetes cluster.  The URL would be the route of the System-Management domain.

We certainly should improve the documentation.

**Comment by davco01a** [comment]
@jantley-ibm @bschrammIBM ^^^^

**Comment by davco01a** [comment]
Can we document a protocol where Champ and Todd are in communication, so that Todd will convey to Champ what this URL is?

@kaczyns How to glean the URL to the Kab instance ?

**Comment by s1cyan** [comment]
docs on the kabanero.io page have been updated on where to get the url
https://kabanero.io/docs/ref/general/kabanero-cli.html#login
