### ISSUE TITLE
Version Handling

### ISSUE THREAD

**Issue by s1cyan** [kabanero-io/kabanero-command-line#87]
If we are not going to be cutting new branches for every version of the CLI how are we handling version numbers
The version is currently hardcoded in the Makefile 
I believe this could possibly be handled with the travis build -but i have not yet gotten to trying to cut a release with travis yet.

**Comment by stephenkinder** [comment]
One possibility is to have the release burn in the version number.

**Comment by s1cyan** [comment]
Is that possible? If the releases trigger some sort of value change in the Makefile, what happens if we build the cli locally? Now that we have the issue with osx needing to be built manually on a mac and uploaded to the release how will that work?
