### ISSUE TITLE
Update management CLI doc for Kabanero 0.2.0 website

### ISSUE THREAD

**Issue by alohr51** [kabanero-io/kabanero-command-line#94]
The Doc needs to be updated before the 0.2.0 release. 

https://github.com/kabanero-io/docs/blob/master/ref/general/kabenero-cli.adoc#kabanero-cli

Some things that need to be updated:

* Instructions on how to install the CLI need to be added
* Login command needs to be updated
* Doc how to get the Kabanero CLI URL (The landing page will display it)
* Mention how to setup the GitHub id 
   * i.e GitHub id needs to be in the group the Kabanero instance is configured with

and a general overview to make sure the rest is accurate/updated.

**Comment by tseelbach** [comment]
at least some of the updates needed are in cli README.md.  How are we suppose to keep README and adoc in sync?   update README continuously and then manually merge into adoc at Release boundary?  or is there a better way?

**Comment by alohr51** [comment]
One option could be only update the adoc in the docs repo and link to it (on kabanero.io) from the CLI README. That way you only have to update 1 doc ever
