### ISSUE TITLE
Something is transmorgrifying IP addresses when using Kab Client from home

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/kabanero-command-line#98]
A number of testers are having trouble reaching Fyre routes for the CLI microservice when working from home using the Cisco VPN

**Comment by davco01a** [comment]
Here are some of the problems seen:

**Comment by davco01a** [comment]
```
Davids-MacBook-Pro:kab-cli2 dacohen@us.ibm.com$ ./kabanero login kabanero-cli-kabanero.thills1.fyre.ibm.com -u davco01a -p xxxxxxxxx
Error: Post https://kabanero-cli-kabanero.thills1.fyre.ibm.com/login: dial tcp: lookup kabanero-cli-kabanero.thills1.fyre.ibm.com on 192.168.1.1:53: no such host
```

**Comment by davco01a** [comment]
Even though ping returns:

ping kabanero-cli-kabanero.thills1.fyre.ibm.com
PING thills1.fyre.ibm.com (9.30.0.192): 56 data bytes
64 bytes from 9.30.0.192: icmp_seq=0 ttl=54 time=83.223 ms

**Comment by davco01a** [comment]
Additionally @brianxjx saw:

[Error] Post https://kabanero-cli-kabanero.thills1.fyre.ibm.com/login: dial tcp: lookup kabanero-cli-kabanero.thills1.fyre.ibm.com on 10.0.0.2:53: no such hos

**Comment by davco01a** [comment]
and @mtamboli saw:

Post https://kabanero-cli-kabanero.natives1.fyre.ibm.com/login: dial tcp: lookup kabanero-cli-kabanero.natives1.fyre.ibm.com on [2600:1700:720:bbf0::1]:53: no such host

**Comment by gecock** [comment]
If this is a generic problem with all VPNs, in other words the Kab CLI is broken using any VPN client, I'd say this is a stop-ship candidate. @stephenkinder what do you think?

**Comment by mtamboli** [comment]
We would really like this fix in the .2 release.

**Comment by davco01a** [comment]
@s1cyan is working on official release version of binary

**Comment by tseelbach** [comment]
This comment https://github.com/golang/go/issues/12524#issuecomment-424529888
says that to produce a Darwin (mac) binary  with CGO_ENABLED=1  one needs to build on a Mac.   That makes sense since CGO is the package that makes hybrid C and Go modules.   

 I don't know if we can build a Mac binary via Travis.

**Comment by tseelbach** [comment]
Based on this post https://github.com/golang/go/issues/12524#issuecomment-526271916
We won't legally be able to cross compile for Darwin on Travis/Linux with CGO_ENABLED
Will have to look at how to compile with CGO_ENABLED *for* Darwin *on* Darwin

**Comment by marikaj123** [comment]
@s1cyan - will the fix be provided this week for release v0.2?

**Comment by s1cyan** [comment]
Yes I will upload the locally built mac binary for the official release on friday so that v0.2 will not have the vpn issue

**Comment by marikaj123** [comment]
@mtamboli - After Claudia's solution is verified, please remove te label 'stopship/ and release-0.2.

**Comment by mtamboli** [comment]
I was able to verify this defect. It was decided to keep this open to make sure that there is a long term solution for this.

**Comment by davco01a** [comment]
I've tested with the 0.2.0 client and the problem is fixed, closing this issue, we can reopen if you encounter again with the 0.2.0 client: https://github.com/kabanero-io/kabanero-command-line/releases/tag/0.2.0

**Comment by gecock** [comment]
@davco01a the plan was to keep this open until a longer term solution was found that wasn't manually building a mac binary each release. If there is another issue that will cover that work, please link to it in here so all parties are aware of the plan moving forward.

**Comment by davco01a** [comment]
Ok, we can leave it open @gecock

**Comment by mtamboli** [comment]
@s1cyan Assuming that you have fix for this issue for long term now? Earlier fix was specific to the last release?

**Comment by davco01a** [comment]
Yes, @s1cyan has an integrated fix with the build process
